export const PERMISSION = Object.freeze(
  {
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',

    SECURE_EXCHANGE: 'SECURE_EXCHANGE',

    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',

    STUDENT_DATA_COLLECTION: 'STUDENT_DATA_COLLECTION',

    MANAGE_EDX_DISTRICT_USERS_PERMISSION: 'MANAGE_EDX_DISTRICT_USERS_PERMISSION',

    MANAGE_EDX_SCHOOL_USERS_PERMISSION: 'MANAGE_EDX_SCHOOL_USERS_PERMISSION',

    VIEW_SCHOOL_PERMISSION: 'VIEW_SCHOOL_PERMISSION',

    VIEW_DISTRICT_PERMISSION: 'VIEW_DISTRICT_PERMISSION',

    VIEW_AUTHORITY_PERMISSION: 'VIEW_AUTHORITY_PERMISSION'
  }
);

export function hasRequiredPermission(userInfo, permission){
  return (userInfo?.userRoles?.filter(perm => perm === permission).length > 0);
};

