const PERMISSION = Object.freeze(
  {
    MANAGE_EDX_DISTRICT_USERS_PERMISSION: 'MANAGE_EDX_DISTRICT_USERS_PERMISSION',
    MANAGE_EDX_SCHOOL_USERS_PERMISSION: 'MANAGE_EDX_SCHOOL_USERS_PERMISSION',
    VIEW_SCHOOL_PERMISSION: 'VIEW_SCHOOL_PERMISSION',
    VIEW_DISTRICT_PERMISSION: 'VIEW_DISTRICT_PERMISSION',
    VIEW_AUTHORITY_PERMISSION: 'VIEW_AUTHORITY_PERMISSION',
    EDIT_SCHOOL_PERMISSION: 'EDIT_SCHOOL_PERMISSION',
    EDIT_DISTRICT_PERMISSION: 'EDIT_DISTRICT_PERMISSION',
    EDIT_INDEPENDENT_SCHOOL_PERMISSION: 'EDIT_INDEPENDENT_SCHOOL_PERMISSION',
    EDIT_OFFSHORE_SCHOOL_PERMISSION: 'EDIT_OFFSHORE_SCHOOL_PERMISSION',
    EDIT_INDEPENDENT_AUTHORITY_PERMISSION: 'EDIT_INDEPENDENT_AUTHORITY_PERMISSION',
    EDIT_OFFSHORE_AUTHORITY_PERMISSION: 'EDIT_OFFSHORE_AUTHORITY_PERMISSION',
    MANAGE_EXCHANGE_PEN_INBOX_PERMISSION: 'MANAGE_EXCHANGE_PEN_INBOX_PERMISSION',
    VIEW_REGISTRATION_CONTACTS_PERMISSION: 'VIEW_REGISTRATION_CONTACTS_PERMISSION',
    REPORTS_SDC_PUBLIC_SCHOOLS_PERMISSION: 'REPORTS_SDC_PUBLIC_SCHOOLS_PERMISSION',
    REPORTS_SDC_INDEPENDENT_SCHOOLS_PERMISSION: 'REPORTS_SDC_INDEPENDENT_SCHOOLS_PERMISSION',
    REPORTS_SDC_HEADCOUNTS_PERMISSION: 'REPORTS_SDC_HEADCOUNTS_PERMISSION',
    MANAGE_EAS_SESSIONS_PERMISSION:'MANAGE_EAS_SESSIONS_PERMISSION',
    VIEW_EAS_STUDENT_PERMISSION: 'VIEW_EAS_STUDENT_PERMISSION',
    EDIT_EAS_STUDENT_PERMISSION: 'EDIT_EAS_STUDENT_PERMISSION',
    MANAGE_EAS_ASSESSMENT_KEYS_PERMISSION:'MANAGE_EAS_ASSESSMENT_KEYS_PERMISSION',
    VIEW_STUDENT_DATA_COLLECTION_PERMISSION: 'VIEW_STUDENT_DATA_COLLECTION_PERMISSION',
    EDIT_STUDENT_DATA_COLLECTION_PERMISSION: 'EDIT_STUDENT_DATA_COLLECTION_PERMISSION',
    VIEW_GDC_REPORTING_PERIOD: 'VIEW_GDC_REPORTING_PERIOD',
  }
);

module.exports = {
  PERMISSION
};

