const PERMISSION = Object.freeze(
  {
    MANAGE_DISTRICT_USERS_PERMISSION: 'MANAGE_DISTRICT_USERS_PERMISSION',
    MANAGE_SCHOOL_USERS_PERMISSION: 'MANAGE_SCHOOL_USERS_PERMISSION',
    VIEW_SCHOOL_PERMISSION: 'VIEW_SCHOOL_PERMISSION',
    VIEW_DISTRICT_PERMISSION: 'VIEW_DISTRICT_PERMISSION',
    VIEW_AUTHORITY_PERMISSION: 'VIEW_AUTHORITY_PERMISSION'
  }
);

module.exports = {
  PERMISSION,
}

