'use strict';
const passport = require('passport');
const express = require('express');
const router = express.Router();
const auth = require('../components/auth');
const utils = require('../components/utils');
const {postNominalRollFile, isBeingProcessed, startProcessing} = require('../components/nominal-roll');
const extendSession = utils.extendSession();
router.post('/', passport.authenticate('jwt', {session: false}, undefined), auth.isValidNominalRollAdmin, extendSession, postNominalRollFile);
router.get('/', passport.authenticate('jwt', {session: false}, undefined), auth.isValidNominalRollAdmin, extendSession, isBeingProcessed);
router.post('/process', passport.authenticate('jwt', {session: false}, undefined), auth.isValidNominalRollAdmin, extendSession, startProcessing);
module.exports = router;
