---
apiVersion: v1
kind: Template
labels: 
  template: student-admin-pipeline
metadata: 
  name: student-admin-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "student-admin-pipeline"
  spec:
    source:
      git:
        uri: "https://github.com/bcgov/EDUC-STUDENT-ADMIN"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile