# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths: 
      - 'frontend/src/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'frontend/src/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run lint:fix
